<!DOCTYPE html>
<html lang="ca">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestió d'Excepcions</title>

    <link rel="alternate" href="https://campusempresa.com/mod/cplusplus/07-02-exception-handling" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/cplusplus/07-02-exception-handling" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/cplusplus/07-02-exception-handling" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="/js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body >
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-12 col-md-8 p-2 p-md-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png"></a>
			</h1>
		</div>
		<div class="col-12 col-md-4 p-2 p-md-0 text-end">
			<h2 id="main_title"><cite>Construint la societat d'avui i del demà</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-2 p-md-0 m-0 text-end">
							<a href="https://enterprisecampus.net/mod/cplusplus/07-02-exception-handling" class="px-2">EN</a></b>
				|
				<a href="https://campusempresa.com/mod/cplusplus/07-02-exception-handling" class="px-2">ES</a></b>
				|
				<b class="px-2">CA</b>
											</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Projecte</a>
				<a href="/about">Sobre nosaltres</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donacions</a>
				<a href="/licence">Llicència</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content">
								<div class='row navigation'>
	<div class='col-2'>
					<a href='07-01-templates' title="Plantilles">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
					<a href="./"><h2 style="text-decoration:underline">Gestió d'Excepcions</h2></a>
			</div>
	<div class='col-2 text-end'>
					<a href='07-03-file-io' title="Entrada/Sortida de Fitxers">Següent &#x25BA;</a>
			</div>
</div>
<div class='content'><p>La gestió d'excepcions és una característica essencial en C++ que permet als programadors manejar errors i situacions excepcionals de manera controlada. En aquest tema, aprendrem com utilitzar les estructures <code>try</code>, <code>catch</code> i <code>throw</code> per gestionar les excepcions en els nostres programes.</p>
</div><h1><p>Conceptes Clau</p>
</h1>
<div class='content'><ol>
<li><strong>Excepció</strong>: Un esdeveniment que interromp el flux normal d'execució d'un programa.</li>
<li><strong>Llançament d'Excepcions (<code>throw</code>)</strong>: La manera de notificar que ha ocorregut una excepció.</li>
<li><strong>Captura d'Excepcions (<code>catch</code>)</strong>: La manera de manejar una excepció llançada.</li>
<li><strong>Blocs <code>try</code></strong>: Blocs de codi on es poden produir excepcions.</li>
</ol>
</div><h1><p>Estructura Bàsica</p>
</h1>
<div class='content'><p>La gestió d'excepcions en C++ es fa mitjançant tres paraules clau: <code>try</code>, <code>catch</code> i <code>throw</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5IHsKICAgIC8vIENvZGkgcXVlIHBvdCBsbGFuw6dhciB1bmEgZXhjZXBjacOzCiAgICB0aHJvdyBleGNlcGNpw7M7Cn0gY2F0Y2ggKHRpcHVzX2V4Y2VwY2nDsyAmZSkgewogICAgLy8gQ29kaSBwZXIgbWFuZWphciBsJ2V4Y2VwY2nDswp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try {
    // Codi que pot llan&ccedil;ar una excepci&oacute;
    throw excepci&oacute;;
} catch (tipus_excepci&oacute; &amp;e) {
    // Codi per manejar l'excepci&oacute;
}</pre></div><div class='content'></div><h2><p>Exemple Pràctic</p>
</h2>
<div class='content'><p>Vegem un exemple pràctic per entendre millor com funciona la gestió d'excepcions.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IGRpdmlkaXIoaW50IGEsIGludCBiKSB7CiAgICBpZiAoYiA9PSAwKSB7CiAgICAgICAgdGhyb3cgcnVudGltZV9lcnJvcigiRGl2aXNpw7MgcGVyIHplcm8gbm8gcGVybWVzYSIpOwogICAgfQogICAgcmV0dXJuIGEgLyBiOwp9CgppbnQgbWFpbigpIHsKICAgIGludCB4ID0gMTA7CiAgICBpbnQgeSA9IDA7CiAgICB0cnkgewogICAgICAgIGludCByZXN1bHRhdCA9IGRpdmlkaXIoeCwgeSk7CiAgICAgICAgY291dCA8PCAiUmVzdWx0YXQ6ICIgPDwgcmVzdWx0YXQgPDwgZW5kbDsKICAgIH0gY2F0Y2ggKGNvbnN0IHJ1bnRpbWVfZXJyb3IgJmUpIHsKICAgICAgICBjb3V0IDw8ICJFcnJvcjogIiA8PCBlLndoYXQoKSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int dividir(int a, int b) {
    if (b == 0) {
        throw runtime_error(&quot;Divisi&oacute; per zero no permesa&quot;);
    }
    return a / b;
}

int main() {
    int x = 10;
    int y = 0;
    try {
        int resultat = dividir(x, y);
        cout &lt;&lt; &quot;Resultat: &quot; &lt;&lt; resultat &lt;&lt; endl;
    } catch (const runtime_error &amp;e) {
        cout &lt;&lt; &quot;Error: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h2><p>Explicació del Codi</p>
</h2>
<div class='content'><ol>
<li><strong>Funció <code>dividir</code></strong>: Aquesta funció pren dos enters <code>a</code> i <code>b</code> i retorna el resultat de la seva divisió. Si <code>b</code> és zero, llança una excepció de tipus <code>runtime_error</code>.</li>
<li><strong>Bloc <code>try</code></strong>: En el <code>main</code>, intentem cridar la funció <code>dividir</code> amb <code>x</code> i <code>y</code>.</li>
<li><strong>Bloc <code>catch</code></strong>: Si es llança una excepció, es captura i es maneja imprimint un missatge d'error.</li>
</ol>
</div><h1><p>Tipus d'Excepcions</p>
</h1>
<div class='content'><p>C++ permet llançar i capturar diferents tipus d'excepcions. Alguns dels tipus més comuns són:</p>
<ul>
<li><strong><code>std::exception</code></strong>: La classe base per a totes les excepcions estàndard.</li>
<li><strong><code>std::runtime_error</code></strong>: Utilitzada per errors que es poden detectar només en temps d'execució.</li>
<li><strong><code>std::logic_error</code></strong>: Utilitzada per errors lògics que es poden detectar en temps de compilació.</li>
</ul>
</div><h2><p>Exemple amb Diversos Tipus d'Excepcions</p>
</h2>
<div class='content'></div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8c3RkZXhjZXB0Pgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKdm9pZCBmdW5jaW8oaW50IHgpIHsKICAgIGlmICh4ID09IDApIHsKICAgICAgICB0aHJvdyBydW50aW1lX2Vycm9yKCJFcnJvciBkZSB0ZW1wcyBkJ2V4ZWN1Y2nDsyIpOwogICAgfSBlbHNlIGlmICh4IDwgMCkgewogICAgICAgIHRocm93IGxvZ2ljX2Vycm9yKCJFcnJvciBsw7JnaWMiKTsKICAgIH0KfQoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIGZ1bmNpbygwKTsKICAgIH0gY2F0Y2ggKGNvbnN0IHJ1bnRpbWVfZXJyb3IgJmUpIHsKICAgICAgICBjb3V0IDw8ICJSdW50aW1lIGVycm9yOiAiIDw8IGUud2hhdCgpIDw8IGVuZGw7CiAgICB9IGNhdGNoIChjb25zdCBsb2dpY19lcnJvciAmZSkgewogICAgICAgIGNvdXQgPDwgIkxvZ2ljIGVycm9yOiAiIDw8IGUud2hhdCgpIDw8IGVuZGw7CiAgICB9CiAgICByZXR1cm4gMDsKfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

void funcio(int x) {
    if (x == 0) {
        throw runtime_error(&quot;Error de temps d'execuci&oacute;&quot;);
    } else if (x &lt; 0) {
        throw logic_error(&quot;Error l&ograve;gic&quot;);
    }
}

int main() {
    try {
        funcio(0);
    } catch (const runtime_error &amp;e) {
        cout &lt;&lt; &quot;Runtime error: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    } catch (const logic_error &amp;e) {
        cout &lt;&lt; &quot;Logic error: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h1><p>Exercicis Pràctics</p>
</h1>
<div class='content'></div><h2><p>Exercici 1</p>
</h2>
<div class='content'><p>Escriu una funció que llegeixi un enter des de l'entrada estàndard i llanci una excepció si el nombre és negatiu. Captura l'excepció i imprimeix un missatge d'error.</p>
<h4>Solució</h4>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8c3RkZXhjZXB0Pgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKdm9pZCBsbGVnaXJOb21icmUoKSB7CiAgICBpbnQgbm9tYnJlOwogICAgY291dCA8PCAiSW50cm9kdWVpeCB1biBub21icmU6ICI7CiAgICBjaW4gPj4gbm9tYnJlOwogICAgaWYgKG5vbWJyZSA8IDApIHsKICAgICAgICB0aHJvdyBpbnZhbGlkX2FyZ3VtZW50KCJOb21icmUgbmVnYXRpdSBubyBwZXJtw6hzIik7CiAgICB9CiAgICBjb3V0IDw8ICJIYXMgaW50cm9kdcOvdDogIiA8PCBub21icmUgPDwgZW5kbDsKfQoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIGxsZWdpck5vbWJyZSgpOwogICAgfSBjYXRjaCAoY29uc3QgaW52YWxpZF9hcmd1bWVudCAmZSkgewogICAgICAgIGNvdXQgPDwgIkVycm9yOiAiIDw8IGUud2hhdCgpIDw8IGVuZGw7CiAgICB9CiAgICByZXR1cm4gMDsKfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

void llegirNombre() {
    int nombre;
    cout &lt;&lt; &quot;Introdueix un nombre: &quot;;
    cin &gt;&gt; nombre;
    if (nombre &lt; 0) {
        throw invalid_argument(&quot;Nombre negatiu no perm&egrave;s&quot;);
    }
    cout &lt;&lt; &quot;Has introdu&iuml;t: &quot; &lt;&lt; nombre &lt;&lt; endl;
}

int main() {
    try {
        llegirNombre();
    } catch (const invalid_argument &amp;e) {
        cout &lt;&lt; &quot;Error: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h2><p>Exercici 2</p>
</h2>
<div class='content'><p>Modifica l'exercici anterior per capturar qualsevol tipus d'excepció i imprimir un missatge genèric d'error.</p>
<h4>Solució</h4>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8c3RkZXhjZXB0Pgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKdm9pZCBsbGVnaXJOb21icmUoKSB7CiAgICBpbnQgbm9tYnJlOwogICAgY291dCA8PCAiSW50cm9kdWVpeCB1biBub21icmU6ICI7CiAgICBjaW4gPj4gbm9tYnJlOwogICAgaWYgKG5vbWJyZSA8IDApIHsKICAgICAgICB0aHJvdyBpbnZhbGlkX2FyZ3VtZW50KCJOb21icmUgbmVnYXRpdSBubyBwZXJtw6hzIik7CiAgICB9CiAgICBjb3V0IDw8ICJIYXMgaW50cm9kdcOvdDogIiA8PCBub21icmUgPDwgZW5kbDsKfQoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIGxsZWdpck5vbWJyZSgpOwogICAgfSBjYXRjaCAoLi4uKSB7CiAgICAgICAgY291dCA8PCAiUydoYSBwcm9kdcOvdCB1biBlcnJvciIgPDwgZW5kbDsKICAgIH0KICAgIHJldHVybiAwOwp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

void llegirNombre() {
    int nombre;
    cout &lt;&lt; &quot;Introdueix un nombre: &quot;;
    cin &gt;&gt; nombre;
    if (nombre &lt; 0) {
        throw invalid_argument(&quot;Nombre negatiu no perm&egrave;s&quot;);
    }
    cout &lt;&lt; &quot;Has introdu&iuml;t: &quot; &lt;&lt; nombre &lt;&lt; endl;
}

int main() {
    try {
        llegirNombre();
    } catch (...) {
        cout &lt;&lt; &quot;S'ha produ&iuml;t un error&quot; &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h1><p>Resum</p>
</h1>
<div class='content'><p>En aquesta secció, hem après els conceptes bàsics de la gestió d'excepcions en C++. Hem vist com utilitzar les estructures <code>try</code>, <code>catch</code> i <code>throw</code> per manejar errors i situacions excepcionals. També hem explorat diferents tipus d'excepcions i hem practicat amb exemples i exercicis pràctics. La gestió d'excepcions és una eina poderosa que ens permet escriure codi més robust i fiable.</p>
</div><div class='row navigation'>
	<div class='col-2'>
					<a href='07-01-templates' title="Plantilles">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
			</div>
	<div class='col-2 text-end'>
					<a href='07-03-file-io' title="Entrada/Sortida de Fitxers">Següent &#x25BA;</a>
			</div>
</div>

			</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicitat</h1>
			<p>Aquest espai està destinat a publicitat.</p>
			<p>Si vols ser patrocinador, contacta amb nosaltres per incloure enllaços en aquesta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>Gràcies per col·laborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Tots els drets reservats</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Acceptar</a>
    <a href="/cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
